### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by 300f20t** [300f20t/Recipe-Generator#3]
## Todo list

- [x] Fix the error of shapeless recipes
- [ ] To eliminate the delay in the development of the Fabric version
- [ ] Add support for Json Recipes
- [ ] Add support for all vanilla blocks for recipes
- [ ] Add the ability to remove all recipes
- [ ] Add recipe removing by input
- [ ] Improve Readme.md
- [ ] Add support for remove by Regex
- [ ] Add GitHub Actions
- [ ] Add and correct translations
- [ ] Improve the Todo list
- [ ] Add support for loops
- [ ] Add visualization of created scripts
- [x] KubeJS???
- [x] Remove Herobrine

**Comment by StoneLegion** [comment]
When you say support for json I assume the way the datapacks / most mods use? I been hunting down for a working in game recipe maker for json/datapack style, without any luck. You seem to be the closest I could fined without the export for json yet.

Thanks.

**Comment by steve-the-player** [comment]
I've got a shapeless recipe from a mod that uses a vanilla bottle and then any block from `#minecraft:planks`, but I want to change the bottle to a modded one. Is there currently a way to use tags as recipe ingredients? 

Also, is there a way to automatically replace an ingredient in a bunch of recipes automatically? For instance if I wanted to change all redstone recipes to require soul torches instead of redstone torches, and have that automatically work for modded redstone components as well, is that possible?

**Comment by 300f20t** [comment]
This is not yet possible without editing the .zs file manually. Check #7

**Comment by CactiCacti** [comment]
Will you ever add compatibility for mods such as AvaratiaNeo with larger crafting grids?

**Comment by 300f20t** [comment]
> Will you ever add compatibility for mods such as AvaratiaNeo with larger crafting grids?

maybe, but it will most likely be difficult to implement for many mods
